config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'
  
	controller :short_urls do
		get '/short_urls/top_100', to: 'short_urls#top_100', as: :short_url_top_100
  end
  resources :short_urls, only: [:new, :index, :create, :show]

  get '/:shortened_url', to: 'short_urls#redirect_to_url', as: :redirect_to_url
  
  root 'short_urls#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
	validates :url, presence: true, uniqueness: true, http_url: true

	after_save :shorten

	def shorten
		shortened_url = self.id.to_s(36)
		update_column(:shortened_url, shortened_url)
		shortened_url
	end

	def unshorten
		self.shortened_url.to_i(36)
	end

	def visit
		self.increment!(:visit_count)
		self.url
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :set_short_url, only: [:show]

  # GET /short_urls
  # GET /short_urls.json
  def index
    @short_urls = ShortUrl.all.order(:url)
  end

  # GET /short_urls/1
  # GET /short_urls/1.json
  def show
  end

  # GET /short_urls/new
  def new
    @short_url = ShortUrl.new
  end

  # POST /short_urls
  # POST /short_urls.json
  def create
    @short_url = ShortUrl.find_by_url(short_url_params[:url])

    @short_url = ShortUrl.new(short_url_params) if @short_url.nil?

    respond_to do |format|
      if @short_url.valid?
        @short_url.save!
        AcquireTitleJob.perform_later(@short_url)

        format.html { redirect_to @short_url, notice: 'Short url was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def redirect_to_url
    short_url = ShortUrl.find_by_shortened_url(params[:shortened_url])
    
    respond_to do |format|
      if short_url.present?
        url = short_url.visit
        format.html { redirect_to url, status: :moved_permanently }
      else
        format.html { render :new, status: :bad_request }
      end
    end
  end

  def top_100
    @short_urls = ShortUrl.all.order(visit_count: :desc).limit(100)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_url
      @short_url = ShortUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def short_url_params
      params.require(:short_url).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortenerofluis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/short_urls/_form.html.erb
<%= form_with(model: short_url, local: true) do |form| %>
  <% if !short_url.nil? && short_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(short_url.errors.count, "error") %> prohibited this short_url from being saved:</h2>

      <ul>
      <% short_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="card-title">Shorten URL</div>
        </div>

         <div class="card-body">
            <div class="form-row">
              <div class="form-group col-md-6">
                <%= form.label :url %><label style="color:red">*</label>
                <%= form.text_field :url, class: 'form-control', placeholder: 'URL', required: true %>
              </div>
            </div>
         </div>

         <div class="card-action">
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= form.submit 'Shorten URL', :class => 'btn btn-primary' %>
              <%= link_to 'Back', short_urls_path, :class => 'btn btn-secondary' %>
            </div>
          </div>
        </div>
    </div>    
  </div>
</div>
<% end %>

app/views/short_urls/index.html.erb
<div class="panel-header">
  <div class="page-inner py-2">
    <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
      <div>
        <h2 class="pb-2 fw-bold">Welcome to Short Url of Luis Eugenio</h2>
        <h5 class="op-7 mb-2 fw-bold">Listing All Short URLs</h5>
      </div>
      <div class="ml-md-auto py-2 py-md-0">
        <%= link_to 'New Short Url', new_short_url_path, :class => 'btn btn-primary' %>
        <%= link_to 'Top 100', short_url_top_100_path, :class => 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

<% if notice %>
  <p id="notice" class="alert alert-warning"><%= notice %></p>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="display table table-bordered table-striped table-hover">
            <thead>
              <tr>
                <th>Url</th>
                <th>Title</th>
                <th>Shortened URL</th>
                <th>Visit Count</th>
              </tr>
            </thead>

            <tbody>
              <% @short_urls.each do |short_url| %>
                <tr>
                  <td><%= short_url.url %></td>
                  <td><%= short_url.title %></td>
                  <td><%= link_to redirect_to_url_url(short_url.shortened_url), redirect_to_url_path(short_url.shortened_url), target: "_blank" %></td>
                  <td><%= short_url.visit_count %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/short_urls/new.html.erb
<%= render 'form', short_url: @short_url %>

app/views/short_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @short_url.url %>
</p>

<p>
  <strong>Shortened Url:</strong>
  <%= link_to redirect_to_url_url(@short_url.shortened_url), redirect_to_url_path(@short_url.shortened_url), target: "_blank" %>
</p>

<%= link_to 'Back', root_path %>

app/views/short_urls/top_100.html.erb
<div class="panel-header">
  <div class="page-inner py-2">
    <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
      <div>
        <h5 class="op-7 mb-2 fw-bold">Top 100 Most Frequently Short Urls</h5>
      </div>
      <div class="ml-md-auto py-2 py-md-0">
        <%= link_to 'Back', short_urls_path, :class => 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="display table table-bordered table-striped table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Url</th>
                <th>Shortened URL</th>
                <th>Visit Count</th>
              </tr>
            </thead>

            <tbody>
              <% @short_urls.each_with_index do |short_url, i| %>
                <tr>
                  <td><%= i+1 %></td>
                  <td><%= short_url.url %></td>
                  <td><%= link_to redirect_to_url_url(short_url.shortened_url), redirect_to_url_path(short_url.shortened_url), target: "_blank" %></td>
                  <td><%= short_url.visit_count %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>